<?php

namespace ISECH\IndicadoresBundle\Entity;

/**
 * LogUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
