<?php

namespace ISECH\IndicadoresBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ISECH\IndicadoresBundle\Entity\MatrizIndicadoresDesempeno;

/**
 * MatrizIndicadoresDesempenoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizIndicadoresDesempenoRepository extends EntityRepository
{
	public function indicadorFichaTecnica()
    {
		return $this->getEntityManager()->getConnection()->executeQuery("SELECT fichatecnica_id as id
			FROM fichatecnica")->fetchAll();
	}
}