<?php

namespace ISECH\IndicadoresBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ISECH\IndicadoresBundle\Entity\MatrizIndicadoresRel;

/**
 * MatrizIndicadoresRelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizIndicadoresRelRepository extends EntityRepository
{
	
}